language: node_js
os:
    - linux
    - windows
    - osx
node_js:
    - "stable"
    - "6"
sudo: false
before_script:
  - npm install -g gulp codecov istanbul
script:
    - gulp
    - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
    - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
